name: Lint Markdown files

on: ["push", "pull_request"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Lint Markdown files
      uses: avto-dev/markdown-lint@v1
      with:
        config: '.markdownlint.json'
        args: '**/*.md .github/**/*.md'
